#!/usr/bin/env python3
"""Export the shared Childgram SVG assets to PNG and Android resources."""

from pathlib import Path
import re
import subprocess
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent
RES = ROOT.parent / "android/dev/res"
SVG = "{http://www.w3.org/2000/svg}"
source = ET.parse(ROOT / "childgram-logo.svg").getroot()
assert source.get("viewBox") == "0 0 1064 1064"
background = source.find(f"{SVG}rect[@id='background']")
symbol = source.find(f"{SVG}g[@id='symbol']")
assert background is not None and symbol is not None
assert len(source) == 3 and all(node.tag == SVG + "path" for node in symbol)
translation = re.fullmatch(r"translate\((-?[\d.]+) (-?[\d.]+)\)", symbol.get("transform", ""))
assert translation, "Expected the logo's translation-only symbol group"
tx, ty = translation.groups()
color = background.attrib["fill"]
paths = "\n".join(
    f'      <path android:fillColor="{node.attrib["fill"]}" android:pathData="{node.attrib["d"]}" />'
    for node in symbol
)


def vector(scale, with_background, size):
    inset = 1064 * (1 - scale) / 2
    fill = (f'  <path android:fillColor="{color}" '
            'android:pathData="M0,0 H1064 V1064 H0 Z" />\n') if with_background else ""
    return f'''<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size}dp" android:height="{size}dp"
    android:viewportWidth="1064" android:viewportHeight="1064">
{fill}  <group android:scaleX="{scale}" android:scaleY="{scale}"
      android:translateX="{inset:g}" android:translateY="{inset:g}">
    <group android:translateX="{tx}" android:translateY="{ty}">
{paths}
    </group>
  </group>
</vector>
'''


files = {
    "mipmap-anydpi/childgram_launcher.xml": vector(1, True, 48),
    # Keep the whole mark inside the central safe area for launcher masks.
    "drawable/childgram_foreground.xml": vector(0.6, False, 108),
    "mipmap-anydpi-v26/childgram_launcher.xml": '''<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/childgram_brand" />
    <foreground android:drawable="@drawable/childgram_foreground" />
    <monochrome android:drawable="@drawable/childgram_foreground" />
</adaptive-icon>
''',
    "values/childgram_branding.xml": f'''<resources>
    <color name="childgram_brand">{color}</color>
</resources>
''',
    # The upstream splash theme references this drawable in day and night mode.
    "drawable/tg_splash_320.xml": vector(0.6, True, 320),
}
assert RES.is_dir(), "Expected the independent Android checkout at ../android"
for name, content in files.items():
    path = RES / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('<?xml version="1.0" encoding="utf-8"?>\n'
                    '<!-- Generated by Childgram branding/export.py; edit the shared SVG. -->\n'
                    + content)
subprocess.run(["rsvg-convert", "-w", "1024", "-h", "1024",
                str(ROOT / "childgram-logo.svg"), "-o", str(ROOT / "childgram-logo.png")], check=True)

usage = ET.parse(ROOT / "childgram-usage.svg").getroot()
attributes = {"fill": "fillColor", "stroke": "strokeColor", "stroke-width": "strokeWidth",
              "stroke-linecap": "strokeLineCap", "stroke-linejoin": "strokeLineJoin", "d": "pathData"}
usage_paths = "\n".join(
    "    <path " + " ".join(f'android:{attributes[key]}="{value if value != "none" else "#00000000"}"'
                           for key, value in node.attrib.items()) + " />"
    for node in usage.findall(SVG + "path")
)
assert usage.get("viewBox") == "0 0 24 24"
(ROOT.parent / "android/TMessagesProj/src/main/res/drawable/childgram_usage.xml").write_text(
    '<?xml version="1.0" encoding="utf-8"?>\n'
    '<!-- Generated by Childgram branding/export.py; edit childgram-usage.svg. -->\n'
    '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
    '    android:width="24dp" android:height="24dp"\n'
    '    android:viewportWidth="24" android:viewportHeight="24">\n'
    + usage_paths + '\n</vector>\n'
)
subprocess.run(["rsvg-convert", "-w", "512", "-h", "512",
                str(ROOT / "childgram-usage.svg"), "-o", str(ROOT / "childgram-usage.png")], check=True)
print("Exported 2 PNGs and 6 Android resources from the shared SVGs")
